[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
]
exceptions = [
    { allow = ["MIT", "Apache-2.0", "Unicode-3.0"], name = "unicode-ident", version = "1" },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"